// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1U5TlgoY5sow_XRH0a4DqahsZ4gxKBg',
    appId: '1:966515661360:web:2bb11651bf4b21b62eebf5',
    messagingSenderId: '966515661360',
    projectId: 'homefind-app',
    authDomain: 'homefind-app.firebaseapp.com',
    storageBucket: 'homefind-app.firebasestorage.app',
    measurementId: 'G-0YD8EEJ6KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBCgBMiueitmejwV3rGXET8SwNdemih8',
    appId: '1:966515661360:android:239e69161d18cc452eebf5',
    messagingSenderId: '966515661360',
    projectId: 'homefind-app',
    storageBucket: 'homefind-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXRst2890PWht3DtEIcIVB8RR3J6QTMo',
    appId: '1:966515661360:ios:477b3f99800cc1df2eebf5',
    messagingSenderId: '966515661360',
    projectId: 'homefind-app',
    storageBucket: 'homefind-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomefind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNXRst2890PWht3DtEIcIVB8RR3J6QTMo',
    appId: '1:966515661360:ios:477b3f99800cc1df2eebf5',
    messagingSenderId: '966515661360',
    projectId: 'homefind-app',
    storageBucket: 'homefind-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomefind',
  );
}
